### ISSUE TITLE
rebase-editor is not visible in ConEmu

### ISSUE THREAD

**Issue by okainov** [sjurba/rebase-editor#24]
1. Install ConEmu
2. Run git bash in it
3. Do rebase
4. Empty terminal will be shown, no errors, but no text neither. If you press Enter, it will say "nothing to do"..

Also tried with -c and with --no-alternate-screen options - it didn't help.

**Comment by sjurba** [comment]
Looks like the integration with the terminal is not working.. And terminals are hard. I'm using terminal-kit for that, and I see that they have done quite a lot of work on that library since my last release. I'll see if I can bump the dependency to the latest version. Maybe that will help.. If you're impatient you could try it your self as well.
